Commands for generation of the MSP430 target compiler
OM4P.Compile OMSPS.Mod/s OMSPB.Mod/s OMSPA.Mod/s OMSPG.Mod/s OMSPP.Mod/s
 OMSPD.Mod/s OMSPTool.Mod/s OMSPX.Mod/s OMSPL.Mod/s ~

Test programs
OMSPP.Compile testFunc.Mod testFor.Mod testDeRef.Mod testCond.Mod testAssert.Mod Traps.Mod msp430g2553.Mod
testIntRelat.Mod Arith.Mod/s testIntArith.Mod testInEx.Mod testInc.Mod testIfThen.Mod testLoadAdr.Mod testNeg.Mod
testParam.Mod testProc.Mod testRecord.Mod testSet.Mod testStore.Mod testString.Mod/s testImportString.Mod
testStringRelat.Mod testTypTag.Mod testSFuncs.Mod testSFuncs2.Mod testSFuncs3.Mod testSProcs.Mod testArray.Mod ~
