M48
; DRILL file {KiCad 7.0.1} date dim. 15 oct. 2023 10:25:20
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-15T10:25:20+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
%
G90
G05
T1
X5.4758Y-5.2888
T2
X6.3026Y-5.2888
T0
M30
